apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin-go-ws-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin-go-ws
  template:
    metadata:
      labels:
        app: store-admin-go-ws
    spec:
      containers:
        - name: store-admin-go-ws-container
          image: store-admin-go-ws:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3040
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "host.docker.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_NAME
              value: "sale-management-system"
            - name: DB_LOGGING
              value: "true"
